# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 892bbf3b867e2926ff57b251353b7589aa92ad4baaa0fba28ea34bfa3484e42ce1aca12489b0c29b057fa84250eb99049a03e181272674a5e1ecc1d69555133e

test:
  secret_key_base: 3b5b1881a960d349b171230f25e1af7245038765860da514288c0a2ca135bf26747569a9898547c1125b3ab6741cdab0f84963dd61e361c2715bdc067543dad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
